<?php
function menu_export_menu() {
    $items = array();
    $items['menu_export'] = array(
        'page callback' => 'menu_export_callback',
        'access arguments' => array('access content'),
	    'delivery callback' => 'drupal_json_output'
     );
    return $items;
}


function menu_export_callback() {
    $menu_main = menu_build_tree('main-menu');
    $menu_footer = menu_build_tree('menu-footer-menu');
    $output = Array();
    
    $output['main'][] = create_main_menu();
    $output['mobile'][] = create_mobile_menu();

    foreach ($menu_footer as $menu_item) {
        $alias = drupal_lookup_path('alias', $menu_item['link']['link_path']);
        $url = $alias ? $alias : $menu_item['link']['link_path'];
        $output['footer'][] = Array('title' => $menu_item['link']['title'], 'link' => $url);
    }
    return drupal_json_output($output);
}
