<?php
/**
 * Implements hook_preprocess_bean().
 */

function spc_home_banner_preprocess_entity(&$vars) {
  $type = $vars['entity_type'];
  if ($type == 'bean') {
    $bean = $vars['bean'];
    $bean_type = $bean->type;
    if ($bean_type == 'home_banner') {
      $search_form = drupal_get_form('ckan_search_form');
      $vars['content']['search_block'] = $search_form;
    }
  }
}

function ckan_search_form($form_state) {
  $form = array();

  $form['term'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#attributes' => array(
      'placeholder' => 'Search'
    )
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => '',
  );

  $form['#submit'] = array('ckan_search_submit');

  return $form;
}

function ckan_search_submit($form, &$form_state) {
  $term = $search_type = $thematic_area = NULL;
  extract($form_state['values'], EXTR_IF_EXISTS);

  switch ($search_type) {
    case 'article':
      $redirect_info = [sprintf('/search/articles/%s/%s', $term, $thematic_area)];
      break;

    case 'dataset':
    default:
      $redirect_info = [
        rtrim(_ckan_tweaks_get_ckan_url()) . '/dataset',
        array(
          'query' => [
            CKAN_SEARCH_NAME_THEMATIC_AREA => $thematic_area,
            'q' => $term
          ]
        )
      ];
      break;
  }

  $form_state['redirect'] = $redirect_info;
}
