<?php

// Search criteria prepared for c-style formatting
const CKAN_SEARCH_NAME_THEMATIC_AREA = 'extras_thematic_area_string';
const CKAN_SEARCH_CRIT_THEMATIC_AREA = CKAN_SEARCH_NAME_THEMATIC_AREA . ':"%s"';

// Additional search param names
const CKAN_SEARCH_PARAM_POPULAR_FIRST = 'ext_popular_first';

// Sorting
const CKAN_SEARCH_SORT_LATEST_FIRST = 'metadata_modified desc';
const CKAN_SEARCH_SORT_MOST_VIEWED_FIRST = 'extras_ga_view_count desc';

// Various static values
const CKAN_DEFAULT_ORG_IMAGE = '/base/images/placeholder-organization.png';

require_once(__DIR__ . DIRECTORY_SEPARATOR . 'ckan_tweaks.helpers.inc');
require_once(__DIR__ . DIRECTORY_SEPARATOR . 'ckan_tweaks.hooks.inc');
