<?php

define('HEALTH_DASHBOARD_URL', '/health-dashboard');

/**
 * Implementation of hook_init().
 */
function spc_health_dashboard_init() {
  if (arg(0) == 'health-dashboard') {
    drupal_add_css(
      drupal_get_path('module', 'spc_health_dashboard') . '/css/spc_health_dashboard.css',
      ['group' => CSS_DEFAULT, 'every_page' => TRUE]
    );
    drupal_add_js(
      drupal_get_path('module', 'spc_health_dashboard') . '/js/spc_health_dashboard.js',
      'file'
    );
    //including D3 library
    drupal_add_js(
      drupal_get_path('module', 'spc_health_dashboard') . '/js/d3.v3.js',
      'file'
    );
    //including Jquery Dialog library
    drupal_add_css(
      drupal_get_path('module', 'spc_health_dashboard') . '/lib/jquery-dialog/jquery-dialog.css',
      ['group' => CSS_DEFAULT, 'every_page' => TRUE]
    );
    drupal_add_js(
      drupal_get_path('module', 'spc_health_dashboard') . '/lib/jquery-dialog/jquery-dialog.js',
      'file'
    );    
  }
}

/**
 * Implements hook_menu().
 */
function spc_health_dashboard_menu() {
  $items = [];

  $items['health-dashboard'] = [
    'title' => t('Health dashboard home page'),
    'description' => t('Health dashboard home page'),
    'page callback' => 'spc_health_dashboard_home_page',
    'access callback' => TRUE,
    'file' => 'inc/dashboard-home.inc',
    'type' => MENU_CALLBACK,
  ];

  $items['health-dashboard/%'] = [
    'title' => t('Health dashboard'),
    'description' => t('Health dashboard'),
    'page callback' => 'spc_health_dashboard_pages',
    'page arguments' => [1],
    'access callback' => TRUE,
    'file' => 'inc/dashboard-categories.inc',
    'type' => MENU_CALLBACK,
  ];

  $items['health-dashboard/%/%'] = [
    'title' => t('Health dashboard'),
    'description' => t('Health dashboard'),
    'page callback' => 'spc_health_dashboard_pages',
    'page arguments' => [1, 2],
    'access callback' => TRUE,
    'file' => 'inc/dashboard-categories.inc',
    'type' => MENU_CALLBACK,
  ];

  $items['health-dashboard/country/%'] = [
    'title' => t('Country'),
    'description' => t('Health dashboard - country'),
    'page callback' => 'spc_health_dashboard_country',
    'page arguments' => [2],
    'access callback' => TRUE,
    'file' => 'inc/dashboard-countries.inc',
    'type' => MENU_CALLBACK,
  ];

  $items['admin/config/health-dashboard'] = [
    'title' => t('Health dashboard settings'),
    'description' => t('Health dashboard settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['spc_health_dashboard_form'],
    'access arguments' => ['access administration pages'],
    'type' => MENU_NORMAL_ITEM,
  ];

  return $items;
}

/**
 * Implements hook_form()
 * Settings form for Health Dashboard.
 */
function spc_health_dashboard_form() {
  $form = [];

  $health_json_fid = (!empty(variable_get('health_json_fid'))) ? variable_get('health_json_fid') : '';

  $form['health_json_file'] = [
    '#type' => 'managed_file',
    '#title' => t('Upload Health JSON File'),
    '#description' => t('Upload a new JSON File her.'),
    '#upload_validators' => [
      'file_validate_extensions' => ['json'],
    ],
    '#process' => ['process_health_json_file'],
    '#upload_location' => 'public://charts/',
    '#default_value' => $health_json_fid,
    '#required' => FALSE,
  ];
  $form['update_categories'] = [
    '#type' => 'checkbox',
    '#title' => t('Update category list'),
    '#default_value' => FALSE,
    '#required' => FALSE,
  ];
  $form['update_countries'] = [
    '#type' => 'checkbox',
    '#title' => t('Update country list'),
    '#default_value' => FALSE,
    '#required' => FALSE,
  ];
  $form['update_indicators'] = [
    '#type' => 'checkbox',
    '#title' => t('Update indicators list'),
    '#default_value' => FALSE,
    '#required' => FALSE,
  ];
  $form['update_default_json'] = [
    '#type' => 'checkbox',
    '#title' => t('Use default JSON file'),
    '#default_value' => FALSE,
    '#required' => FALSE,
  ];
  $form['markup1'] = [
    '#markup' => _array_print_helper(variable_get('health_dashboard_categories_list', []), 'Categories array'),
    '#weight' => 20,
  ];
  $form['markup2'] = [
    '#markup' => _array_print_helper(variable_get('health_dashboard_countries', []), 'Countries array'),
    '#weight' => 20,
  ];
  $form['markup5'] = [
    '#markup' => _array_print_helper(variable_get('health_dashboard_indicators', []), 'Indicators array'),
    '#weight' => 20,
  ];
  $form['markup4'] = [
    '#markup' => _array_print_helper(variable_get('health_dashboard_json', ''), 'Path to JSON'),
    '#weight' => 20,
  ];

  $form['#validate'][] = 'spc_health_dashboard_form_validate';
  $form['#submit'][] = 'spc_health_dashboard_form_submit';
  return system_settings_form($form);
}


/**
 * Form json process.
 */
function process_health_json_file($element, &$form_state, $form) {
  $element = file_managed_file_process($element, $form_state, $form);
  $element['upload_button']['#access'] = FALSE;
  return $element;
}

/**
 * Validate handler for the custom form.
 */
function spc_health_dashboard_form_validate($form, &$form_state) {
  $validators = [];
  if ($file_health_json = file_save_upload('health_json_file', $validators)) {
    $form_state['values']['health_json_file'] = $file_health_json;
    variable_set('health_json_fid', $form_state['values']['health_json_file']->fid);
  }
  else {
    form_set_error('file', 'No file was uploaded.');
  }
}

/**
 * Submit handler for the custom form.
 */
function spc_health_dashboard_form_submit($form, &$form_state) {
  // On category list change.
  if (!empty($form_state['values']['update_categories'])) {
    spc_health_dashboard_update_categories();
  }
  // On country list change.
  if (!empty($form_state['values']['update_countries'])) {
    spc_health_dashboard_update_countries();
  }
  // On indicators list change.
  if (!empty($form_state['values']['update_indicators'])) {
    spc_health_dashboard_update_indicators();
  }
  // On default JSON.
  if (!empty($form_state['values']['update_default_json'])) {
    $json_path = base_path() . drupal_get_path('module', 'spc_health_dashboard') . '/default.json';
    variable_set('health_dashboard_json', $json_path);
    drupal_set_message('New file was uploaded. (Not really for now)');
  }
  // On file upload.
  if (!empty($form_state['values']['health_json_file'])) {
    $file_health_json = $form_state['values']['health_json_file'];
    $file_health_json->status = FILE_STATUS_PERMANENT;
    file_save($file_health_json);

    $json_path = file_create_url($file_health_json->uri);
    variable_set('health_dashboard_json', $json_path);

    drupal_set_message('New file was uploaded.');
  }
}

/**
 * Updates the category list.
 */
function spc_health_dashboard_update_categories() {

  $category_list = [
    'leadership-and-governance' => [
      '#title' => t('Leadership and governance'),
      '#wrapper' => FALSE,
      '#weight' => 0,
      '#indicators' => [
        'multi-sectoral-ncd-taskforce' => t('Multi-sectoral NCD taskforce'),
        'national-strategy-addressing-ncds-and-risk-factors' => t('National strategy addressing NCDs and risk factors'),
        'explicit-ncd-indicators-and-targets' => t('Explicit NCD indicators and targets'),
      ],
    ],
    'tobacco' => [
      '#title' => t('Tobacco'),
      '#wrapper' => t('Preventive policies'),
      '#weight' => 1,
      '#indicators' => [
        'tobacco-excise-taxes' => t('Tobacco excise taxes'),
        'smoke-free-environments' => t('Smoke-free environments'),
      ],
    ],
    'alcohol' => [
      '#title' => t('Alcohol'),
      '#wrapper' => t('Preventive policies'),
      '#weight' => 2,
      '#indicators' => [
        'alcohol-licencing-to-restrict-sales' => t('Alcohol licencing to restrict sales'),
        'alcohol-advertising' => t('Alcohol advertising'),
      ],
    ],
    'food' => [
      '#title' => t('Food'),
      '#wrapper' => t('Preventive policies'),
      '#weight' => 3,
      '#indicators' => [
        'reducing-salt-consumption' => t('Reducing salt consumption'),
        'trans-fats' => t('Trans-fats'),
        'unhealthy-food-marketing-to-children' => t('Unhealthy food marketing to children'),
        'food-fiscal-policies' => t('Food fiscal policies'),
        'healthy-food-policies-in-schools' => t('Healthy food policies in schools'),
        'food-based-dietary-guidelines' => t('Food-based dietary guidelines'),        
      ],
    ], 
    'physical-activity' => [
      '#title' => t('Physical activity'),
      '#wrapper' => t('Preventive policies'),
      '#weight' => 4,
      '#indicators' => [
        'compulsory-physical-education-in-school-curriculum' => t('Compulsory physical education in school curriculum'),       
      ],
    ], 
    'enforcement' => [
      '#title' => t('Enforcement'),
      '#wrapper' => t('Preventive policies'),
      '#weight' => 5,
      '#indicators' => [
        'enforcement-of-laws-and-regulations-related-to-ncd-risk-factors' => t('Enforcement of laws and regulations related to NCD risk factors'),       
      ],
    ],
    'health-system' => [
      '#title' => t('Health system response programmes'),
      '#wrapper' => FALSE,
      '#weight' => 5,
      '#indicators' => [
        'national-guidelines-for-care-of-main-ncds' => t('National guidelines for care of main NCDs'),
        'essential-drugs' => t('Essential drugs'),
        'smoking-cessation' => t('Smoking cessation'),
        'marketing-of-breast-milk-substitutes' => t('Marketing of breast milk substitutes'),
        'baby-friendly-hospitals' => t('Baby friendly hospitals'),
        'maternity-leave-and-breastfeeding' => t('Maternity leave and breastfeeding'),
      ],
    ],    
    'monitoring' => [
      '#title' => t('Monitoring'),
      '#wrapper' => FALSE,
      '#weight' => 10,
      '#indicators' => [
        'population-risk-factor-prevalence-surveys-adults' => t('Population risk factor prevalence surveys - adults'),
        'population-risk-factor-prevalence-surveys-youth' => t('Population risk factor prevalence surveys - youth'),
        'child-growth-monitoring' => t('Child growth monitoring'),
        'routine-cause-specific-mortality' => t('Routine cause-specific mortality'),
      ],
    ],
  ];

  variable_set('health_dashboard_categories_list', $category_list);
  drupal_set_message('Categories were updated.');
}

/**
 * Updates the country list.
 */
function spc_health_dashboard_update_countries() {

  $countries = [
    'american-samoa' => [  //in JSON with real data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'American Samoa', 
      '#abbr' => NULL,
    ],
    'commonwealth-of-the-northern-mariana-islands' => [ //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Commonwealth of the Northern Mariana Islands',
      '#abbr' => 'CNMI',
    ],
    'cook-islands' => [ //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Cook Islands',
      '#abbr' => NULL,
    ],
    'federated-states-of-micronesia' => [ //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Federated States of Micronesia',
      '#abbr' => 'FSM',
    ],
    'fiji' => [ //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Fiji',
      '#abbr' => NULL,
    ],
    'french-polynesia' => [ //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'French Polynesia',
      '#abbr' => NULL,
    ],
    'guam' => [ //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Guam',
      '#abbr' => NULL,
    ],
    'kiribati' => [ //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Kiribati',
      '#abbr' => NULL,
    ],
    'nauru' => [  //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Nauru',
      '#abbr' => NULL,
    ],
    'niue' => [ //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Niue',
      '#abbr' => NULL,
    ],
    'new-caledonia' => [  //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'New Caledonia',
      '#abbr' => NULL,
    ],
    'palau' => [  //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Palau',
      '#abbr' => NULL,
    ],
    'papua-new-guinea' => [ //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Papua New Guinea',
      '#abbr' => 'PNG',
    ],
    'republic-of-the-marshall-islands' => [ //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Republic of the Marshall Islands',
      '#abbr' => 'RMI',
    ],
    'tokelau' => [  //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Tokelau',
      '#abbr' => NULL,
    ],
    'tonga' => [  //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Tonga',
      '#abbr' => NULL,
    ],
    'samoa' => [  //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Samoa',
      '#abbr' => NULL,
    ],
    'solomon-islands' => [  //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Solomon Islands',
      '#abbr' => NULL,
    ],
    'tuvalu' => [ //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Tuvalu',
      '#abbr' => NULL,
    ],
    'vanuatu' => [  //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Vanuatu',
      '#abbr' => NULL,
    ],
    'wallis-and-futuna' => [  //in JSON with default data.
      '#icon_big' => NULL,
      '#icon_small' => NULL,
      '#title' => 'Wallis and Futuna',
      '#abbr' => NULL,
    ],
  ];

  variable_set('health_dashboard_countries', $countries);
  drupal_set_message('Countries were updated.');
}

/**
 * Updates the indicators list.
 */
function spc_health_dashboard_update_indicators() {
  $indicators = [
    'not-applicable' => 'Not applicable',
    'not-present' => 'Not present',
    'under-development' => 'Under development',
    'present' => 'Present',
    'low' => 'Low',
    'medium' => 'Medium',
    'high' => 'High',
  ];
  
  variable_set('health_dashboard_indicators', $indicators);
  drupal_set_message('Indicators were updated.');
}

/**
 * Returns HTML output to print arrays.
 *
 * @param $arr array
 * Any array.
 * @param $summary string
 * summary string (optional).
 *
 * @return string
 * Formatted output.
 */
function _array_print_helper($arr, $summary = '') {
  $output = '<details>';
  $output .= '<summary>' . $summary . '</summary>';
  $output .= '<pre>';
  $output .= print_r($arr, TRUE);
  $output .= '</pre></details>';
  return $output;
}

/**
 * Implements hook_theme().
 */
function spc_health_dashboard_theme() {
  return [
    'spc_health_dashboard_page' => [
      'variables' => [
        'title' => NULL,
        'breadcrumbs' => NULL,
        'search' => NULL,
        'content' => NULL,
        'subtitle' => NULL,
      ],
      'template' => 'templates/spc_health_dashboard_page',
    ],
    'spc_health_dashboard_breadcrumbs' => [
      'variables' => [
        'breadcrumbs' => NULL,
      ],
      'template' => 'templates/spc_health_dashboard_breadcrumbs',
    ],
    'spc_health_dashboard_home_search' => [
      'variables' => [
        'search' => NULL,
      ],
      'template' => 'templates/spc_health_dashboard_home_search',
    ],
    'spc_health_dashboard_home_content' => [
      'variables' => [
        'data' => NULL,
      ],
      'template' => 'templates/spc_health_dashboard_home_content',
    ],
    'spc_health_dashboard_country_content' => [
      'variables' => [
        'data' => NULL,
      ],
      'template' => 'templates/spc_health_dashboard_country_content',
    ],    
  ];
}

/**
 * Returns dashboard data from uploaded file.
 *
 * @return array
 * Dashboard data array.
 */
function get_health_dashboard_data() {

  $health_json_fid = (!empty(variable_get('health_json_fid'))) ? variable_get('health_json_fid') : '';

  if (!empty($health_json_fid)) {
    $file = file_load($health_json_fid);
    $uri = $file->uri;

    if ($health_dashboard_data = file_get_contents($uri)) {
      $data = json_decode($health_dashboard_data, TRUE);
    }
    else {
      $data = get_health_dashboard_default_data();
    }
  }
  else {
    $data = get_health_dashboard_default_data();
  }

  return $data;
}

/**
 * Returns dashboard demo data from default file.
 *
 * @return array
 * Dashboard data array.
 */
function get_health_dashboard_default_data() {

  $data = [];

  if ($spc_health_dashboard = file_get_contents(drupal_get_path('module', 'spc_health_dashboard') . '/default.json')) {
    $data = json_decode($spc_health_dashboard, TRUE);
  }

  return $data;
}

/**
 * Returns dashboard home search template.
 *
 * @return array
 * Content data array.
 */
function spc_health_dashboard_home_search() {
  $data = array();
  
  $content = theme('spc_health_dashboard_home_search', array('search' => $data));
  
  return $content;
}
